
//-------------------------------------------
//----------USER ACCOUNT MANAGEMENT----------
//-------------------------------------------
//Check if user exists.
POST https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/authentication/userExists

{
   "email": "oasis@oasis-alltracker.com"
}
###

//Refresh token.
POST https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/authentication/refreshToken
Authorization: Bearer token

###

//Request OTP.
POST https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/authentication/requestOTP

{
   "email": "hodgerta@gmail.com",
   "password": "1234"
}
###

//Login with OTP.
POST https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/authentication/loginOTP

{
   "email": "hodgerta@gmail.com",
   "otp": "7549"
}
###

//Request new password.
POST https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/authentication/requestNewPassword

{
   "email": "hodgerta@gmail.com"
}
###

// Verify temp password
POST https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/authentication/verifyTempPassword

{
   "email": "hodgerta@gmail.com",
   "tempPassword": "GNErTpqsQG"
}
###

//Create new password.
POST https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/authentication/createNewPassword

{
   "email": "hodgerta@gmail.com",
   "tempPassword": "xHbNjOIwGL",
   "password": "1234"
}
###





//---------------------------------------------------------------------------------------------------------------
//----------   -------         ----      APP      ------    ----------   --------------  ----------     ---------
//---------------------------------------------------------------------------------------------------------------


//-------------------------------------------
//--------------- p r o f i l e -------------
//-------------------------------------------
GET https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzQwNDIwMCwiZXhwIjoxNzI3NTc3MDAwfQ.RR4ypU42NI0w4ExAWQmv8x7CmS86NVlmKJkVZ0Mgzk0
###
PUT https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzQwNDIwMCwiZXhwIjoxNzI3NTc3MDAwfQ.RR4ypU42NI0w4ExAWQmv8x7CmS86NVlmKJkVZ0Mgzk0

{
    "location": 80304,
    "activities": [
        {
            "activity": "basketball",
            "skill": 3
        },
        {
            "activity": "volleyball",
            "skill": 4
        }
    ],
    "availabilities": [
        {
            "timeOfDay": "afternoon",
            "dayOfWeek": 2
        },
        {
            "timeOfDay": "afternoon",
            "dayOfWeek": 3
        },
        {
            "timeOfDay": "afternoon",
            "dayOfWeek": 0
        }

    ],
    "friends": ["player2", "player4"]
}
###
POST https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsImlhdCI6MTcyNzQwNDE0NSwiZXhwIjoxNzI3NTc2OTQ1fQ.ioO3McO9buL2jEd5DhvBC4wEpYoJl09fbnJRP9DYVYA

{
    "location": 80304,
    "activities": [
        {
            "activity": "basketball",
            "skill": 3
        },
        {
            "activity": "volleyball",
            "skill": 4
        }
    ],
    "availabilities": [
        {
            "timeOfDay": "morning",
            "dayOfWeek": 2
        },
                {
            "timeOfDay": "afternoon",
            "dayOfWeek": 2
        }
    ],
    "playerID": "player1"
}
###

//-------------------------------------------
//--------------- f r i e n d s -------------
//-------------------------------------------
GET https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/friends
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzQwNDIwMCwiZXhwIjoxNzI3NTc3MDAwfQ.RR4ypU42NI0w4ExAWQmv8x7CmS86NVlmKJkVZ0Mgzk0
###

DELETE https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/friends/player4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzQwNDIwMCwiZXhwIjoxNzI3NTc3MDAwfQ.RR4ypU42NI0w4ExAWQmv8x7CmS86NVlmKJkVZ0Mgzk0
###


//-------------------------------------------
//---------------- s q u a d s --------------
//-------------------------------------------
GET https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/squads
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzQwNDIwMCwiZXhwIjoxNzI3NTc3MDAwfQ.RR4ypU42NI0w4ExAWQmv8x7CmS86NVlmKJkVZ0Mgzk0
###

GET https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/squads/watt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzQwNDIwMCwiZXhwIjoxNzI3NTc3MDAwfQ.RR4ypU42NI0w4ExAWQmv8x7CmS86NVlmKJkVZ0Mgzk0
###

POST https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/squads
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzQwNDIwMCwiZXhwIjoxNzI3NTc3MDAwfQ.RR4ypU42NI0w4ExAWQmv8x7CmS86NVlmKJkVZ0Mgzk0

{
    "squadID": "wattt"
}
###

DELETE https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/squads/wattt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzQwNDIwMCwiZXhwIjoxNzI3NTc3MDAwfQ.RR4ypU42NI0w4ExAWQmv8x7CmS86NVlmKJkVZ0Mgzk0
###


//-------------------------------------------
//--------------- i n v i t e s -------------
//-------------------------------------------
GET https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/invites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzQwNDIwMCwiZXhwIjoxNzI3NTc3MDAwfQ.RR4ypU42NI0w4ExAWQmv8x7CmS86NVlmKJkVZ0Mgzk0
###
PUT https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/invites/{inviteID}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzQwNDIwMCwiZXhwIjoxNzI3NTc3MDAwfQ.RR4ypU42NI0w4ExAWQmv8x7CmS86NVlmKJkVZ0Mgzk0

{
    "didAccept": false,
    "inviteType": "game",
    "inviteID": {
        "gamePK": "basketball-80304",
        "gameSK": "20241122-x4dssadsdf"
    }
}
###
POST https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/invites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzQwNDIwMCwiZXhwIjoxNzI3NTc3MDAwfQ.RR4ypU42NI0w4ExAWQmv8x7CmS86NVlmKJkVZ0Mgzk0

{
    "inviteType": "game",
    "inviteID": {
        "gamePK": "80304-game",
        "gameSK": "20240923-d351b9b0-7d57-11ef-bf3b-11c09764b1b0"
    },
    "playerID": "oasis"
}
###


//-------------------------------------------
//----------------- g a m e s ---------------
//-------------------------------------------
GET https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/games/20240923-d351b9b0-7d57-11ef-bf3b-11c09764b1b0?gamePK=80304-game&gameSK=20240923-d351b9b0-7d57-11ef-bf3b-11c09764b1b0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzQwNDIwMCwiZXhwIjoxNzI3NTc3MDAwfQ.RR4ypU42NI0w4ExAWQmv8x7CmS86NVlmKJkVZ0Mgzk0
###
POST https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/games
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzQwNDIwMCwiZXhwIjoxNzI3NTc3MDAwfQ.RR4ypU42NI0w4ExAWQmv8x7CmS86NVlmKJkVZ0Mgzk0

{
    "activity": "basketball",
    "startTime": "5:00",
    "endTime": "17:00",
    "coordinates": "123,12314",
    "isOpen": true,
    "name": "NBRC pickup",
    "playerCount": 0,
    "description": "Fun pickup",
    "minPlayers": 4,
    "maxPlayers": 20,
    "level": 3,
    "dateStamp": "20240923",
    "location": 80304
}
###
PUT https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/games/gameID
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzQwNDIwMCwiZXhwIjoxNzI3NTc3MDAwfQ.RR4ypU42NI0w4ExAWQmv8x7CmS86NVlmKJkVZ0Mgzk0

{
    "activity": "basketball",
    "startTime": "6:00",
    "endTime": "17:00",
    "coordinates": "123,12314",
    "isOpen": true,
    "name": "NBRC pickup",
    "playerCount": 0,
    "description": "Fun pickup",
    "minPlayers": 4,
    "maxPlayers": 22,
    "level": 3,
    "dateStamp": "20240923",
    "location": 80304,
    "gameCreator": "player1",
    "PK": "80304-game",
    "SK": "20241103-f47391d0-79de-11ef-a422-2b5f7ec9aadf"
}
###

//-------------------------------------------
//---------- g a m e S t a t u s ------------
//-------------------------------------------
PUT https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/gameStatus
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzM3NTU4NiwiZXhwIjoxNzI3NTQ4Mzg2fQ.5M6dWFiqgbEZikAupxwuAY7ezGO6hEJNR4Maw0t-LJM

{
    "playerID": "player1",
    "status": "join",
    "startTime": "8:00",
    "endTime": "11:30",
    "coordinates": "123,12314",
    "gamePK": "80304-game",
    "gameSK": "20240923-d351b9b0-7d57-11ef-bf3b-11c09764b1b0"
}
###

//-------------------------------------------
//----- r e g i s t e r e d G a m e s -------
//-------------------------------------------
GET https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/registeredGames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzM3NTU4NiwiZXhwIjoxNzI3NTQ4Mzg2fQ.5M6dWFiqgbEZikAupxwuAY7ezGO6hEJNR4Maw0t-LJM
###

//-------------------------------------------
//------ s u g g e s t e d G a m e s --------
//-------------------------------------------
GET https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/suggestedGames?dateStamp=20240923
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzExNDcyOCwiZXhwIjoxNzI3Mjg3NTI4fQ.whkSJwYRQsvsuWp03DG4bEKNpcsfPdR1--DHt1IIgmQ
###

//-------------------------------------------
//- p l a y e r A v a i l a b i l i t i e s -
//-------------------------------------------
GET https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/playerAvailabilities
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzExMDU0MCwiZXhwIjoxNzI3MjgzMzQwfQ.8w5iBzgWGqsVl_e3zgntcOj_AO9BaxNwsSC3HvcsyWk
###
POST https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/playerAvailabilities
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzExMDU0MCwiZXhwIjoxNzI3MjgzMzQwfQ.8w5iBzgWGqsVl_e3zgntcOj_AO9BaxNwsSC3HvcsyWk

{
    "startTime": "12:00",
    "endTime": "16:00",
    "dateStamp": "20241124",
    "activity": "basketball",
    "location": 80304,
    "skill": 3
}
###
DELETE https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/playerAvailabilities
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzExMDU0MCwiZXhwIjoxNzI3MjgzMzQwfQ.8w5iBzgWGqsVl_e3zgntcOj_AO9BaxNwsSC3HvcsyWk
###

//-------------------------------------------
//----- a v a i l a b l e P l a y e r s -----
//-------------------------------------------
GET https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/availablePlayers?activity=basketball&location=80304&proximity=10&dateStamp=20241124&time=1700
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzExMDU0MCwiZXhwIjoxNzI3MjgzMzQwfQ.8w5iBzgWGqsVl_e3zgntcOj_AO9BaxNwsSC3HvcsyWk
###

//-------------------------------------------
//------- a v a i l a b l e G a m e s -------
//-------------------------------------------
GET https://zy33ts7f57.execute-api.us-east-1.amazonaws.com/dev/v1/availableGames?activity=basketball&location=80304&proximity=10&dateStamp=20241103&time=1700
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZGdlcnRhQGdtYWlsLmNvbSIsInBsYXllcklEIjoicGxheWVyMSIsImlhdCI6MTcyNzExMDU0MCwiZXhwIjoxNzI3MjgzMzQwfQ.8w5iBzgWGqsVl_e3zgntcOj_AO9BaxNwsSC3HvcsyWk
###